### ISSUE TITLE
get syntax highlighting set up and working

### ISSUE THREAD

**Issue by tomjoht** [tomjoht/documentation-theme-jekyll-next-version#20]

**Comment by tomjoht** [comment]
I think syntax highlighting is working, but I haven't tested it out. Also, I kind of like darker backgrounds with code samples. I'm not sure.

**Comment by nsjalind** [comment]
![screen shot 2016-12-13 at 11 13 49 pm](https://cloud.githubusercontent.com/assets/24510747/21169370/8cc389fc-c189-11e6-87ae-43c6fa3839ba.png)

Is this what the issue means? Darker background  (gray) and syntax highlighting (different colors according to code categories) ?

**Comment by nsjalind** [comment]
testing 
```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```
